### ISSUE TITLE
InternalError

### ISSUE THREAD

**Issue by diadistis** [sweble/sweble-wikitext#35]
Please replace java.lang.InternalError with a more appropriate exception. InternalError signifies an unrecoverable error in the JVM.

Thanks

**Comment by hannesd** [comment]
Throwing InternalError was indeed a bad idea. Throwing AssertionError instead would be more appropriate. I wonder, however, if that fits your bill. After all, both exceptions are not meant to be caught. Do you want/need to catch the exception, or is it just the wrong use of InternalError that's bothering you? In the latter case I would replace InternalError with AssertionError.

**Comment by diadistis** [comment]
Is there a reason that you want to use an exception that is not meant to be caught for invalid input? A quick search shows about 15 `InternalError` exceptions so I would consider it per case. `AssertionError` is still a [very strong exception](http://stackoverflow.com/questions/24863185/what-is-an-assertionerror-in-which-case-should-i-throw-it-from-my-own-code) and I wouldn't use it, because invalid user input (and we can safely consider wikipedia data as user input) is meant to be handled. In my case I just had to wrap the calls to `postprocess` and `go` in a catch `Throwable` and re-throw my own exception so a higher level can handle the situation.

**Comment by hannesd** [comment]
InternalError should not be thrown for invalid input. If that's the case in the code that would be yet another mistake. InternalError is thrown when execution reaches a point that it should not be able to reach (that at least was my intention back then). Postprocessing is quite a complex state machine and there are some corner cases that should not be reachable. In these cases I used InternalError although it should probably have been AssertionError. They are not meant to be caught because they don't indicate erroneous input (wikitext cannot have syntax errors). It's an error in the parser code (and my understanding) that has to be fixed.

Please submit a small snippet of wikitext that will cause the InternalError and I can have a look at it. In any case, I will replace InternalError with AssertionError (or something else, depending on the situation).

**Comment by diadistis** [comment]
I can see what you mean. In that case you're probably right but I have several cases that cause problems. I will open separate issue for each problem but the simplest I can remember right now is just a simple `PRE` tag. It happens only when it's upper-case and currently it crashes on the [Dynamic Programming](https://en.wikipedia.org/w/api.php?action=query&titles=Dynamic%20programming&export&exportnowrap) page.

**Comment by kno10** [comment]
The `PRE` tag issue is detailed here: #43 
The tag extension is not applied to uppercase `PRE` tags.

**Comment by hannesd** [comment]
Fixed in version 2.2.0
