### ISSUE TITLE
cite template not parsed

### ISSUE THREAD

**Issue by sirpy** [sweble/sweble-wikitext#60]
<ref>{{cite web|url=http://www.billboard.com/articles/news/56447/dreamgirls-snares-multiple-golden-globe-nods|title='Dreamgirls' Snares Multiple Golden Globe Nods|date=December 14, 2006|author=Kilday, Gregg|work=[[The Hollywood Reporter]]}}</ref>

it's parsed as WtTagExtension, is there some parser to convert this template into it's components?

**Comment by hannesd** [comment]
I'm confused. That's clearly a template and if I plug this piece of wikitext into the parser I get an WtTemplate AST. Are you using the swc-engine and performing expansion? Could you paste the AST you get (only the relevant part)?

**Comment by sirpy** [comment]
i'm using the TextConverter example
if i put break points in the different visit() methods it stops at WtTagExtension and not WtTemplate

**Comment by hannesd** [comment]
I'm assuming you are talking about the TextConverter class in sweble-wom3-example-basic version 3.*?

This class has some copy and paste errors (no big problem because it's commented out). The use of type WtTemplate is nonsensical in this context since we are working with WOM nodes and not the AST nodes produced by the parser. The equivalent for WtTemplate in WOM is SwcTransclusion (the tag extension class is SwcTagExtension). If I added the following methods to the TextConverter class:

```java

	public void visit(Wom3Node n)
	{
		// Fallback for all nodes that are not explicitly handled below
		/*write("<");
		write(n.getNodeName());
		write(" />");
		*/
		iterate(n);
	}

	public void visit(SwcTransclusion n)
	{
		System.out.println("template");
	}
	
	public void visit(SwcTagExtension n)
	{
		System.out.println("tagExtension");
	}
	
```

The output is "template" which is what I would expect and consider correct. Does this fix your problem?

**Comment by sirpy** [comment]
i think it does. i will test
