### ISSUE TITLE
No parsing of text inside <ref>?

### ISSUE THREAD

**Issue by wetneb** [sweble/sweble-wikitext#67]
Hi!
After some investigation, it looks like things enclosed by XML tags are not parsed further. For instance:
<pre>
Groundbreaking claim.&lt;ref&gt;see {{cite book|author=Chuck Norris|title=The Truth}}&lt;/ref&gt;
</pre>
The citation template will not be parsed at all: the content of the `<ref>...</ref>` is just represented as a String.

I understand this might be desirable for tags like `<nowiki/>` but I'm not sure why this would apply to any tag? How could I modify the parser to recurse inside the `<ref>`?

**Comment by hannesd** [comment]
The behavior you describe only applies to tags that were configured as tag extensions in the parser (through the config). Tag extensions are basically functions that are free to choose what they want to do with their content. Therefore the parser cannot just parse their content because there's a good chance the content isn't even wikitext.

I took a look at the engine code and the &lt;math> and &lt;ref> extension have nonsensical implementations (return null). You have two options here:

a) Remove the math and ref tag extension from the configuration. They should then be treated as unknown XML elements and their content would get parsed.

b) Properly implement the extension you require. Here's just an example how one could parse the extension's content in the MathTagExtImpl.invoke(...) method of the tag extension:

```
try
{
	EngProcessedPage processed = frame.getEngine().parseAndPostprocess(
			new PageId(frame.getTitle(), -1L),
			body.getContent(),
			null);
	EngPage page = processed.getPage();
	return nf().unwrap(page);
}
catch (EngineException e)
{
	return nf().softError("Processing of <math> tag failed");
}
```

I cannot guarantee that this code actually works as I have not tested it.

**Comment by wetneb** [comment]
@hannesd awesome, thanks a lot!
